/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddPatientInsuranceRequest } from './models/AddPatientInsuranceRequest';
export type { AddPatientRelativeRequest } from './models/AddPatientRelativeRequest';
export { AiAuditLog } from './models/AiAuditLog';
export type { AiChatRequest } from './models/AiChatRequest';
export type { AiChatResponse } from './models/AiChatResponse';
export type { AiOperationalInsightDto } from './models/AiOperationalInsightDto';
export type { AlternativeCode } from './models/AlternativeCode';
export type { ApiResponseAiChatResponse } from './models/ApiResponseAiChatResponse';
export type { ApiResponseAiOperationalInsightDto } from './models/ApiResponseAiOperationalInsightDto';
export type { ApiResponseAppointmentDto } from './models/ApiResponseAppointmentDto';
export type { ApiResponseAuthUserDto } from './models/ApiResponseAuthUserDto';
export type { ApiResponseBranchOperationalHeatmapDto } from './models/ApiResponseBranchOperationalHeatmapDto';
export type { ApiResponseCdsAdviceDto } from './models/ApiResponseCdsAdviceDto';
export type { ApiResponseClinicalChecklistDto } from './models/ApiResponseClinicalChecklistDto';
export type { ApiResponseClinicalEarlyWarningDto } from './models/ApiResponseClinicalEarlyWarningDto';
export type { ApiResponseComplicationRiskDto } from './models/ApiResponseComplicationRiskDto';
export type { ApiResponseConsultationDetailDto } from './models/ApiResponseConsultationDetailDto';
export type { ApiResponseConsultationDto } from './models/ApiResponseConsultationDto';
export type { ApiResponseDifferentialDiagnosisDto } from './models/ApiResponseDifferentialDiagnosisDto';
export type { ApiResponseDoctorDashboardDto } from './models/ApiResponseDoctorDashboardDto';
export type { ApiResponseDoctorInfoDto } from './models/ApiResponseDoctorInfoDto';
export type { ApiResponseFollowUpSuggestionDto } from './models/ApiResponseFollowUpSuggestionDto';
export type { ApiResponseHealthMetric } from './models/ApiResponseHealthMetric';
export type { ApiResponseHealthThresholdDto } from './models/ApiResponseHealthThresholdDto';
export type { ApiResponseIcd10CodeDto } from './models/ApiResponseIcd10CodeDto';
export type { ApiResponseInvoiceDto } from './models/ApiResponseInvoiceDto';
export type { ApiResponseListAppointmentDto } from './models/ApiResponseListAppointmentDto';
export type { ApiResponseListConsultationDto } from './models/ApiResponseListConsultationDto';
export type { ApiResponseListDailyVolumeDto } from './models/ApiResponseListDailyVolumeDto';
export type { ApiResponseListDiagnosticImageDto } from './models/ApiResponseListDiagnosticImageDto';
export type { ApiResponseListDoctorInfoDto } from './models/ApiResponseListDoctorInfoDto';
export type { ApiResponseListHealthMetric } from './models/ApiResponseListHealthMetric';
export type { ApiResponseListHealthMetricDto } from './models/ApiResponseListHealthMetricDto';
export type { ApiResponseListHealthThresholdDto } from './models/ApiResponseListHealthThresholdDto';
export type { ApiResponseListInvoiceDto } from './models/ApiResponseListInvoiceDto';
export type { ApiResponseListLabResultDto } from './models/ApiResponseListLabResultDto';
export type { ApiResponseListMedicalServiceDto } from './models/ApiResponseListMedicalServiceDto';
export type { ApiResponseListMedicationReminderDto } from './models/ApiResponseListMedicationReminderDto';
export type { ApiResponseListMedicationSchedule } from './models/ApiResponseListMedicationSchedule';
export type { ApiResponseListPatientChatConversationDto } from './models/ApiResponseListPatientChatConversationDto';
export type { ApiResponseListPatientChatMessageDto } from './models/ApiResponseListPatientChatMessageDto';
export type { ApiResponseListPatientChronicCondition } from './models/ApiResponseListPatientChronicCondition';
export type { ApiResponseListPatientInsuranceDto } from './models/ApiResponseListPatientInsuranceDto';
export type { ApiResponseListPatientNotificationDto } from './models/ApiResponseListPatientNotificationDto';
export type { ApiResponseListPatientRelativeDto } from './models/ApiResponseListPatientRelativeDto';
export type { ApiResponseListPatientVitalTarget } from './models/ApiResponseListPatientVitalTarget';
export type { ApiResponseListSlotAvailabilityDto } from './models/ApiResponseListSlotAvailabilityDto';
export type { ApiResponseListSlotTemplateDto } from './models/ApiResponseListSlotTemplateDto';
export type { ApiResponseListTenant } from './models/ApiResponseListTenant';
export type { ApiResponseListTenantBranchDto } from './models/ApiResponseListTenantBranchDto';
export type { ApiResponseListTenantDto } from './models/ApiResponseListTenantDto';
export type { ApiResponseListTimelineItemDto } from './models/ApiResponseListTimelineItemDto';
export type { ApiResponseListTriageVitalDto } from './models/ApiResponseListTriageVitalDto';
export type { ApiResponseListVitalHistoryDto } from './models/ApiResponseListVitalHistoryDto';
export type { ApiResponseListVitalTrendDto } from './models/ApiResponseListVitalTrendDto';
export type { ApiResponseLoginResponse } from './models/ApiResponseLoginResponse';
export type { ApiResponseMapStringObject } from './models/ApiResponseMapStringObject';
export type { ApiResponseMapStringString } from './models/ApiResponseMapStringString';
export type { ApiResponseMedicalServiceDto } from './models/ApiResponseMedicalServiceDto';
export type { ApiResponseMedicationDosageLogDto } from './models/ApiResponseMedicationDosageLogDto';
export type { ApiResponseMedicationSchedule } from './models/ApiResponseMedicationSchedule';
export type { ApiResponsePagedResponseAiAuditLog } from './models/ApiResponsePagedResponseAiAuditLog';
export type { ApiResponsePagedResponseAppointmentDto } from './models/ApiResponsePagedResponseAppointmentDto';
export type { ApiResponsePagedResponseConsultationDto } from './models/ApiResponsePagedResponseConsultationDto';
export type { ApiResponsePagedResponsePatientDto } from './models/ApiResponsePagedResponsePatientDto';
export type { ApiResponsePagedResponsePrescriptionDto } from './models/ApiResponsePagedResponsePrescriptionDto';
export type { ApiResponsePatientChatMessageDto } from './models/ApiResponsePatientChatMessageDto';
export type { ApiResponsePatientChronicCondition } from './models/ApiResponsePatientChronicCondition';
export type { ApiResponsePatientCrmInsightDto } from './models/ApiResponsePatientCrmInsightDto';
export type { ApiResponsePatientDashboardDto } from './models/ApiResponsePatientDashboardDto';
export type { ApiResponsePatientDto } from './models/ApiResponsePatientDto';
export type { ApiResponsePatientInsuranceDto } from './models/ApiResponsePatientInsuranceDto';
export type { ApiResponsePatientRelativeDto } from './models/ApiResponsePatientRelativeDto';
export type { ApiResponsePatientVitalLogDto } from './models/ApiResponsePatientVitalLogDto';
export type { ApiResponsePatientVitalTarget } from './models/ApiResponsePatientVitalTarget';
export type { ApiResponsePrescription } from './models/ApiResponsePrescription';
export type { ApiResponsePrescriptionDto } from './models/ApiResponsePrescriptionDto';
export type { ApiResponsePrescriptionVerificationDto } from './models/ApiResponsePrescriptionVerificationDto';
export type { ApiResponseStandardizedClinicalNoteDto } from './models/ApiResponseStandardizedClinicalNoteDto';
export type { ApiResponseString } from './models/ApiResponseString';
export type { ApiResponseTenant } from './models/ApiResponseTenant';
export type { ApiResponseTenantBranchDto } from './models/ApiResponseTenantBranchDto';
export type { ApiResponseTenantDto } from './models/ApiResponseTenantDto';
export type { ApiResponseTreatmentEfficacyDto } from './models/ApiResponseTreatmentEfficacyDto';
export type { ApiResponseVoid } from './models/ApiResponseVoid';
export type { ApiResponseWaitTimeSummaryDto } from './models/ApiResponseWaitTimeSummaryDto';
export type { AppointmentDto } from './models/AppointmentDto';
export type { AuthUserDto } from './models/AuthUserDto';
export type { BranchOperationalHeatmapDto } from './models/BranchOperationalHeatmapDto';
export type { CareGap } from './models/CareGap';
export type { CdsAdviceDto } from './models/CdsAdviceDto';
export type { CdsSuggestion } from './models/CdsSuggestion';
export type { CdsWarning } from './models/CdsWarning';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export type { ChatMessage } from './models/ChatMessage';
export type { ClinicalChecklistDto } from './models/ClinicalChecklistDto';
export type { ClinicalConsultation } from './models/ClinicalConsultation';
export type { ClinicalEarlyWarningDto } from './models/ClinicalEarlyWarningDto';
export type { ComplicationRiskDto } from './models/ComplicationRiskDto';
export type { ConsultationDetailDto } from './models/ConsultationDetailDto';
export type { ConsultationDto } from './models/ConsultationDto';
export type { CptCode } from './models/CptCode';
export type { CreateAppointmentRequest } from './models/CreateAppointmentRequest';
export type { CreateBranchRequest } from './models/CreateBranchRequest';
export type { CreateConsultationRequest } from './models/CreateConsultationRequest';
export type { CreatePatientRequest } from './models/CreatePatientRequest';
export type { CreatePrescriptionRequest } from './models/CreatePrescriptionRequest';
export type { CreateTenantRequest } from './models/CreateTenantRequest';
export type { DailyVolumeDto } from './models/DailyVolumeDto';
export type { DiagnosticImageDto } from './models/DiagnosticImageDto';
export type { DifferentialDiagnosisDto } from './models/DifferentialDiagnosisDto';
export type { DifferentialItem } from './models/DifferentialItem';
export type { Doctor } from './models/Doctor';
export type { DoctorCreateAppointmentRequest } from './models/DoctorCreateAppointmentRequest';
export type { DoctorDashboardDto } from './models/DoctorDashboardDto';
export type { DoctorInfoDto } from './models/DoctorInfoDto';
export type { FollowUpSuggestionDto } from './models/FollowUpSuggestionDto';
export type { HealthMetric } from './models/HealthMetric';
export type { HealthMetricDto } from './models/HealthMetricDto';
export type { HealthThresholdDto } from './models/HealthThresholdDto';
export type { Icd10Code } from './models/Icd10Code';
export type { Icd10CodeDto } from './models/Icd10CodeDto';
export type { IdentityRole } from './models/IdentityRole';
export type { IdentityUser } from './models/IdentityUser';
export type { IdentityUserRole } from './models/IdentityUserRole';
export type { InvoiceDto } from './models/InvoiceDto';
export type { InvoiceItemDto } from './models/InvoiceItemDto';
export type { ItemRequest } from './models/ItemRequest';
export type { LabResultDto } from './models/LabResultDto';
export type { LocalTime } from './models/LocalTime';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { MedicalServiceDto } from './models/MedicalServiceDto';
export type { Medication } from './models/Medication';
export type { MedicationDosageLogDto } from './models/MedicationDosageLogDto';
export type { MedicationReminderDto } from './models/MedicationReminderDto';
export type { MedicationSchedule } from './models/MedicationSchedule';
export type { MetricInsight } from './models/MetricInsight';
export type { OptimizationSuggestion } from './models/OptimizationSuggestion';
export type { Pageable } from './models/Pageable';
export type { PagedResponseAiAuditLog } from './models/PagedResponseAiAuditLog';
export type { PagedResponseAppointmentDto } from './models/PagedResponseAppointmentDto';
export type { PagedResponseConsultationDto } from './models/PagedResponseConsultationDto';
export type { PagedResponsePatientDto } from './models/PagedResponsePatientDto';
export type { PagedResponsePrescriptionDto } from './models/PagedResponsePrescriptionDto';
export type { Patient } from './models/Patient';
export type { PatientChatConversationDto } from './models/PatientChatConversationDto';
export type { PatientChatMessageDto } from './models/PatientChatMessageDto';
export type { PatientChronicCondition } from './models/PatientChronicCondition';
export type { PatientCrmInsightDto } from './models/PatientCrmInsightDto';
export type { PatientDashboardDto } from './models/PatientDashboardDto';
export type { PatientDto } from './models/PatientDto';
export type { PatientInsuranceDto } from './models/PatientInsuranceDto';
export type { PatientNotificationDto } from './models/PatientNotificationDto';
export type { PatientRelativeDto } from './models/PatientRelativeDto';
export type { PatientVitalLogDto } from './models/PatientVitalLogDto';
export type { PatientVitalTarget } from './models/PatientVitalTarget';
export { Prescription } from './models/Prescription';
export type { PrescriptionDto } from './models/PrescriptionDto';
export type { PrescriptionItemDto } from './models/PrescriptionItemDto';
export type { PrescriptionVerificationDto } from './models/PrescriptionVerificationDto';
export type { RegisterDeviceTokenRequest } from './models/RegisterDeviceTokenRequest';
export type { RegisterFcmTokenRequest } from './models/RegisterFcmTokenRequest';
export type { RegisterRequest } from './models/RegisterRequest';
export type { RiskFactor } from './models/RiskFactor';
export type { RiskPatientDto } from './models/RiskPatientDto';
export type { SchedulingAppointment } from './models/SchedulingAppointment';
export type { SendAdviceRequest } from './models/SendAdviceRequest';
export type { SendChatMessageRequest } from './models/SendChatMessageRequest';
export type { SendChatNotificationRequest } from './models/SendChatNotificationRequest';
export type { SlotAvailabilityDto } from './models/SlotAvailabilityDto';
export type { SlotTemplateDto } from './models/SlotTemplateDto';
export type { SocialLoginRequest } from './models/SocialLoginRequest';
export type { StandardizedClinicalNoteDto } from './models/StandardizedClinicalNoteDto';
export type { Tenant } from './models/Tenant';
export type { TenantBranch } from './models/TenantBranch';
export type { TenantBranchDto } from './models/TenantBranchDto';
export type { TenantDto } from './models/TenantDto';
export type { TimelineItemDto } from './models/TimelineItemDto';
export type { TreatmentEfficacyDto } from './models/TreatmentEfficacyDto';
export type { TriageVitalDto } from './models/TriageVitalDto';
export type { UpdateHealthThresholdRequest } from './models/UpdateHealthThresholdRequest';
export type { UpdatePatientProfileRequest } from './models/UpdatePatientProfileRequest';
export type { UpdatePatientRequest } from './models/UpdatePatientRequest';
export type { UpdatePrescriptionRequest } from './models/UpdatePrescriptionRequest';
export type { UpdateTenantSettingsRequest } from './models/UpdateTenantSettingsRequest';
export type { VerificationWarning } from './models/VerificationWarning';
export type { VitalHistoryDto } from './models/VitalHistoryDto';
export type { VitalTrendDto } from './models/VitalTrendDto';
export type { VitalWarning } from './models/VitalWarning';
export type { WaitTimeSummaryDto } from './models/WaitTimeSummaryDto';

export { AiAuditService } from './services/AiAuditService';
export { AnalyticsService } from './services/AnalyticsService';
export { AuthService } from './services/AuthService';
export { ChatNotificationService } from './services/ChatNotificationService';
export { ChronicManagementService } from './services/ChronicManagementService';
export { ClinicalService } from './services/ClinicalService';
export { ClinicManagementService } from './services/ClinicManagementService';
export { DoctorAdvisoryService } from './services/DoctorAdvisoryService';
export { DoctorAiSupportService } from './services/DoctorAiSupportService';
export { DoctorAppointmentsService } from './services/DoctorAppointmentsService';
export { DoctorConsultationService } from './services/DoctorConsultationService';
export { DoctorDashboardService } from './services/DoctorDashboardService';
export { DoctorHealthMonitoringService } from './services/DoctorHealthMonitoringService';
export { DoctorMessagingService } from './services/DoctorMessagingService';
export { DoctorPatientManagementService } from './services/DoctorPatientManagementService';
export { DoctorPrescriptionsService } from './services/DoctorPrescriptionsService';
export { DoctorProfileService } from './services/DoctorProfileService';
export { EhrService } from './services/EhrService';
export { HealthService } from './services/HealthService';
export { HealthTrackingService } from './services/HealthTrackingService';
export { MasterDataService } from './services/MasterDataService';
export { MedicationManagementService } from './services/MedicationManagementService';
export { PatientService } from './services/PatientService';
export { PatientAiService } from './services/PatientAiService';
export { PatientAppointmentsService } from './services/PatientAppointmentsService';
export { PatientBillingService } from './services/PatientBillingService';
export { PatientBranchesService } from './services/PatientBranchesService';
export { PatientClinicalService } from './services/PatientClinicalService';
export { PatientMedicationService } from './services/PatientMedicationService';
export { PatientMessagingService } from './services/PatientMessagingService';
export { PatientPortalNotificationsService } from './services/PatientPortalNotificationsService';
export { PatientProfileService } from './services/PatientProfileService';
export { PrescriptionService } from './services/PrescriptionService';
export { ReportService } from './services/ReportService';
export { SchedulingService } from './services/SchedulingService';
export { SystemAdminService } from './services/SystemAdminService';
export { TenantService } from './services/TenantService';
